travis:
  secure:
    BINSTAR_TOKEN: h3ltkXieldCl0b2XAm7Mk+M3rjhQme/TYJL8ItQ/aahmYYf/k9VcCbLF8eCgtGaty/OTs8bFK/yMJfz/9ThL3zRYy+gmW/VyJyM3WyQ/WDUnH85oZVikaffLDKW8jFtiUOZV9Ri1n1Ci3/vQQDdriWwqWhwDNXNwZkQ8dn7P9AsApB8THcmF1Lc2puWoyaSHzLpBVFsFddaMzoIDCY0LPzBRAAiXiEcEOXwuj7cbMuVaGbCMfUbgns3oURdudDrOSGlqxwFSbLMVJlcaMA8knNRkRwMNicWoJpxckljL4BgVW1T1zUE1vOpSwv/djDT7ISbkjKQP6Aky38Jnez4qL7TCBW7ijKfjl6xeJKEd1O/BYRg0rKq1qgyhNiaCh1O1b4JWAjW+EkDDHRmU1iOEJS8dpDy8fXXbCbflvbACZRRwa3YYS7w9YsQjDEVB6bFNqcZ5qAZrVqZyzug0AC4J7h3JifGSEXmqJlem5JCj6ISwkZojEiRjUkmnluVxtPZmCyJnlP6EteS5s3WQLvvnwf8sBdriRQXo3jI/8JVjFHAK5W+zCh5KDeBpk91vNFf44cYu6vwobGAhIOHO5nIMBaI6S75u8v1IdpCEmMTRQFwxS1A3xPicTbdhFhe5OQCtWwEtGX62WHty4CvC9FseN21srixBDZ/NrvXe0CNgpD4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
